# 生产环境配置

# 数据源配置
spring:
  datasource:
    url: jdbc:mysql://47.242.50.132:3306/purchase?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ostudio007
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# 日志配置
logging:
  file:
    name: purchase.log
  level:
    root: WARN
    com.egao: ERROR
    com.baomidou.mybatisplus: ERROR
